interfaces:
  linecard:
    0:
      slot:
        0:
          port:
            0:
              #shutdown: False
              #mtu: 1518
              function: metro
              encapsulation: dot1q
              phy: ge
              lldp: enabled
              units:
                - id: 132
                  #interface_name: core_P1  #Generated based on {{function}}_{{neighbor}} and stored in router_interface.yml
                  function: metro
                  neighbor: P4
                  neighbor_port: 1/1/5
                  inet: 10.10.22.4
                  mask: 31
                  ospf:
                    area: 0.0.0.0
                    type: point-to-point
            1:
              shutdown: False
              function: metro
              lldp: enabled
              neighbor: P3
              neighbor_port: ge-0/0/5
              encapsulation: dot1q
              phy: ge
              units:
                - id: 137
                  function: metro
                  neighbor: P3
                  neighbor_port: ge-0/0/5
                  inet: 10.10.22.6
                  mask: 31
                  ospf:
                    area: 0.0.0.0
                    type: point-to-point
            2:
              shutdown: False
              function: core
              phy: ge
              encapsulation: 'null'
              neighbor: RADIUS01
              neighbor_port: ens4
              inet: 192.168.0.1
              mask: 24
              ospf:
                area: 0.0.0.0
                passive: True
                shutdown: False
                bfd: disabled
            3:
              shutdown: False
              function: access
              lldp: enabled
              neighbor: CE03
              neighbor_port: ge-0/0/2
              encapsulation: dot1q
              phy: ge
