---
- include_vars:
    dir: "{{ hostvar_dir }}"
    extensions: [yml]

- include_vars:
    dir: "{{ base_dir }}/group_vars/MPLS_Multi"
    extensions: [yml]    

- name: Purge and delete any previous build_dir
  file: path={{ build_dir }} state=absent

- name: Create build_dir
  file: path={{ build_dir }} state=directory

- name: Generate ALU config in parts
  template: src="alu_{{ item.key }}.j2" dest="{{ build_dir }}/{{ item.value }}_{{ item.key }}.conf.part"
  with_dict: 
    system: 1
    interface: 2
    ospf: 3
    bgp: 4
    mpls: 5

- name: Assemble and generate ALU complete configuration
  assemble:
    src: "{{ build_dir }}"
    dest: "{{ config_dir }}/{{ inventory_hostname }}_complete.conf"
    regexp: "_*conf.part"

- name: Generate flat sros config file from generated templated config
  script: "{{ base_dir }}/scripts/sros_to_flat.py {{ config_dir }}/{{inventory_hostname}}_complete.conf > {{ config_dir }}/{{inventory_hostname}}_flat_complete.conf"
