interfaces:
  linecard:
    0:
      slot:
        0:
          port:
            1:
              function: metro
              encapsulation: dot1q
              phy: ge
              units:
                - id: 131
                  function: metro
                  neighbor: P4
                  neighbor_port: 1/1/5:131
                  inet: 10.10.21.4
                  ospf:
                    area: 0.0.0.0
            2:
              function: metro
              encapsulation: dot1q
              phy: ge
              units:
                - id: 136
                  function: metro
                  neighbor: P3
                  neighbor_port: ge-0/0/5.136
                  inet: 10.10.21.6
                  ospf:
                    area: 0.0.0.0
