interfaces:
  linecard:
    0:
      slot:
        0:
          port:
            1:
              shutdown: False
              function: core
              phy: ge
              encapsulation: ethernet
              neighbor: P2
              neighbor_port: Gi0/0/0/1
              inet: 10.10.10.0
              mask: 31
              ospf:
                area: 0.0.0.0
                type: point-to-point
                #metric: 200
                shutdown: True
            2:
              #shutdown: False
              #mtu: 1518
              function: core
              encapsulation: dot1q
              phy: ge
              lldp: enabled
              units:
                - id: 10
                  function: core
                  neighbor: RR3
                  neighbor_port: 1/1/2
                  inet: 10.10.0.13
                  mask: 31
                  ospf:
                    area: 0.0.0.0
                    type: point-to-point
                    md5: "{{ global.ospf.md5 }}"
                - id: 20
                  function: core
                  neighbor: RR1
                  neighbor_port: ge-0/0/3
                  inet: 10.10.0.5
                  mask: 31
                  ospf:
                    area: 0.0.0.0
                    type: point-to-point
                - id: 30
                  function: core
                  neighbor: P4
                  neighbor_port: 1/1/1
                  inet: 10.10.10.6
                  mask: 31
                  ospf:
                    area: 0.0.0.0
                    type: point-to-point
                    metric: 100
            5:
              function: metro
              encapsulation: dot1q
              phy: ge
              units:
                - id: 101
                  function: metro
                  neighbor: PE05
                  neighbor_port: 1/1/1
                  inet: 10.10.22.1
                  ospf:
                    area: 0.0.0.0
                    type: point-to-point
                - id: 102
                  function: metro
                  neighbor: S-PE04
                  neighbor_port: 1/1/1
                  inet: 10.10.31.5
                  ospf:
                    area: 8.0.0.4
                    type: point-to-point
                - id: 103
                  function: metro
                  neighbor: PE03
                  neighbor_port: Gi0/0/0/1
                  inet: 10.10.21.1
                  ospf:
                    area: 0.0.0.0
                    type: point-to-point
            6:
              function: metro
              encapsulation: dot1q
              phy: ge
              units:
                - id: 111
                  function: metro
                  neighbor: S-PE01
                  neighbor_port: ge-0/0/1
                  inet: 10.10.30.1
                  ospf:
                    area: 8.0.0.1
                    type: point-to-point
                - id: 112
                  function: metro
                  neighbor: E-PE01
                  neighbor_port: ge-0/0/1
                  inet: 10.10.40.1
                  ospf:
                    area: 0.0.0.0
                    type: point-to-point
                - id: 113
                  function: metro
                  neighbor: PE01
                  neighbor_port: ge-0/0/1
                  inet: 10.10.20.1
                  ospf:
                    area: 0.0.0.0
                    type: point-to-point
