interfaces:
  linecard:
    0:
      slot:
        0:
          port:
            1:
              #shutdown: False
              #mtu: 1518
              function: metro
              encapsulation: dot1q
              phy: ge
              lldp: enabled
              units:
                - id: 141
                  function: metro
                  neighbor: P2
                  neighbor_port: Gi0//0/0/6
                  inet: 10.10.30.4
                  ospf:
                    area: 8.0.0.2
            2:
              shutdown: False
              function: metro
              encapsulation: dot1q
              phy: ge
              units:
                - id: 146
                  function: metro
                  neighbor: P3
                  neighbor_port: ge-0/0/6
                  inet: 10.10.30.6
                  ospf:
                    area: 8.0.0.2
