interfaces:
  linecard:
    0:
      slot:
        0:
          port:
            0:
              #shutdown: False
              #mtu: 1518
              function: metro
              encapsulation: dot1q
              phy: ge
              lldp: enabled
              units:
                - id: 101
                  #interface_name: core_P1  #Generated based on {{function}}_{{neighbor}} and stored in router_interface.yml
                  function: metro
                  neighbor: P1
                  neighbor_port: ge-0/0/5
                  inet: 10.10.22.0
                  mask: 31
                  ospf:
                    area: 0.0.0.0
            1:
              shutdown: False
              function: metro
              lldp: enabled
              neighbor: P2
              neighbor_port: Gi0/0/0/5
              encapsulation: dot1q
              phy: ge
              units:
                - id: 106
                  function: metro
                  neighbor: P2
                  neighbor_port: Gi0/0/0/5
                  inet: 10.10.22.2
                  mask: 31
                  ospf:
                    area: 0.0.0.0
                    #metric: 500
            3:
              shutdown: False
              function: access
              lldp: enabled
              neighbor: CE02
              neighbor_port: ge-0/0/1
              encapsulation: dot1q
              phy: ge
