interfaces:
  linecard:
    0:
      slot:
        0:
          port:
            1:
              shutdown: False
              function: core
              phy: ge
              encapsulation: ethernet
              neighbor: RR3
              neighbor_port: 1/1/1
              inet: 10.10.0.0
              ospf:
                area: 0.0.0.0
            2:
              function: core
              encapsulation: ethernet
              phy: ge
              lldp: enabled
              neighbor: RR2
              neighbor_port: Gi0/0/0/2
              inet: 10.10.0.2
              ospf:
                area: 0.0.0.0
            3:
              function: core
              encapsulation: dot1q
              phy: ge
              units:
                - id: 20
                  function: core
                  neighbor: P1
                  neighbor_port: ge-0/0/2
                  inet: 10.10.0.4
                  ospf:
                    area: 0.0.0.0
            4:
              function: core
              encapsulation: ethernet
              phy: ge
              neighbor: P2
              neighbor_port: Gi0/0/0/4
              inet: 10.10.0.6
              ospf:
                area: 0.0.0.0
            5:
              function: core
              encapsulation: dot1q
              phy: ge
              units:
                - id: 21
                  function: core
                  neighbor: P3
                  neighbor_port: ge-0/0/1
                  inet: 10.10.0.8
                  ospf:
                    area: 0.0.0.0
            6:
              function: core
              encapsulation: dot1q
              phy: ge
              units:
                - id: 50
                  function: core
                  neighbor: P4
                  neighbor_port: 1/1/1
                  inet: 10.10.0.10
                  ospf:
                    area: 0.0.0.0
